<a href="https://colab.research.google.com/github/horainkhattak/Python-data-analysis-notes/blob/main/practicenumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.linspace(1,3,5)
arr

array([1. , 1.5, 2. , 2.5, 3. ])

In [ ]:
np.random.rand(10)

array([0.62923477, 0.22648129, 0.56282947, 0.97826175, 0.76421287,
       0.81844242, 0.42486653, 0.50083438, 0.32045536, 0.80293769])

In [ ]:
np.random.randn(20)

array([-1.69371682, -0.59815706, -0.38000103, -1.11502884,  0.12080332,
        0.29397513,  0.76681573,  0.24128168,  0.76980079, -0.06854251,
       -0.46985815, -0.96720724,  0.06425828,  0.67557936, -0.31414634,
        1.40977545,  0.40970948,  0.4438029 ,  0.17398143,  0.46762041])

In [ ]:
np.random.randint(7)

6

In [ ]:
np.random.randint(10,30,5)

array([18, 10, 14, 29, 27])

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[8,9,2]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 2]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 2]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max(

)

np.int64(9)

In [ ]:
arr.sum()

np.int64(40)

In [ ]:
np.sum(arr,axis=0)

array([13, 16, 11])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 19])

In [ ]:
arr.mean()

np.float64(4.444444444444445)

In [ ]:
arr.std()

np.float64(2.629368792488718)

In [ ]:
arr.argmax()

np.int64(7)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Array indexing and slicing**

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[6]

np.int64(17)

In [ ]:
arr[2:7]

array([13, 14, 15, 16, 17])

In [ ]:
arr[:5]

array([11, 12, 13, 14, 15])

In [ ]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[1:5:3]

array([12, 15])

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[:,0]

array([ 1,  6, 11, 16, 21, 26])

In [ ]:
arr[0,1]

np.int64(2)

In [ ]:
arr[1,0]

np.int64(6)

In [ ]:
slice=arr[3:5,2:4]
slice

array([[18, 19],
       [23, 24]])

In [ ]:
slice=arr[3:6,3:6]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr4=np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
bool_index=arr4%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [ ]:
arr = arr[bool_index]
print(arr)

NameError: name 'arr' is not defined

**Array operation**

Arithmatic operation


In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [ ]:
l=[10,20,30,40]
arr=np.array(l)

In [ ]:
arr+10

array([20, 30, 40, 50])

In [ ]:
arr2=np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

**Deep copy Shallow copy**

In [ ]:
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
slice=a[1:5]
slice+10

array([12, 13, 14, 15])

Real array mai kuch change nai hua toh this is **shallow copy** but in list change hota hai


In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
b=a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
b[0]=3

Change hua toh it is a **deep copy**

In [ ]:
a

array([ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

**Matrix Operation**

In [ ]:
A=np.array([[2,3],[4,5]])
B=np.array([[6,7],[8,9]])

In [ ]:
C=A@B
C

array([[36, 41],
       [64, 73]])

**Transpose**

In [ ]:
A

array([[2, 3],
       [4, 5]])

In [ ]:
A.T

array([[2, 4],
       [3, 5]])

In [ ]:
C.T

array([[36, 64],
       [41, 73]])

**Advance Array Manipulaton**

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

Vertical Stack

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Horizontal Stack

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

Column Stack

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting **

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Horizontal Split**

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
fruits = ["apple", "banana", "mango"]

for fruit in fruits:
    print(fruit)

apple
banana
mango
